on:
  push:
    branches:
      - master

name: Create Release from version.txt

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get version
        id: vars
        run: echo "version=$(cat version.txt)" >> $GITHUB_ENV
        # run: echo ::set-output name=version::$(cat version.txt)
      - name: Test output
        run: echo "${{ env.version }}"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: |
            cat version.txt
          release_name: |
            cat version.txt
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
